### ISSUE TITLE
Question about Model

### ISSUE THREAD

**Issue by Tianyi-Billy-Ma** [georgeguo-cn/LGMRec#2]
In the file models/lgmrec.py line 118, why assign the gumble_softmax value of ut_hyper to uv_hyper?

The source code is ```uv_hyper = F.gumbel_softmax(ut_hyper, self.tau, dim=1, hard=False)```.

Isn't this should be ```ut_hyper = F.gumbel_softmax(ut_hyper, self.tau, dim=1, hard=False)```?

**Comment by georgeguo-cn** [comment]
Thank you for your thorough inspection. You are right and I have made the following modifications: 

```ut_hyper = F.gumbel_softmax(ut_hyper, self.tau, dim=1, hard=False)```.

**Comment by MeycL** [comment]
@georgeguo-cn Could you please provide the results after the code update?

**Comment by georgeguo-cn** [comment]
Hi @MeycL , thank you for your attention to our paper.

Here are the experimental results after applying the fix:
| Datasets | R@10 | R@20 | N@10 | N@20 |
| -- | -- | -- | -- | -- |
| Baby | 0.0647 | 0.0992 | 0.0353 | 0.0442 |
| Sports | 0.0716 | 0.1085 | 0.0390 | 0.0485 |
| Clothing | 0.0556 | 0.0825 | 0.0302 | 0.0370 |

The parameter settings are as follows:
| Parameters | L | K | H | A | α | ρ | λ1 | λ2 |
| -- | -- | -- | -- | -- | -- | -- | -- | -- |
| Baby | 4 | 2 | 1 | 4 | 0.3 | 0.5 | 1e−6 | 1e−4 |
| Sports | 4 | 2 | 1 | 4 | 0.6 | 0.4 | 1e−6 | 1e−4 |
| Clothing | 4 | 2 | 2 | 64 | 0.2 | 0.2 | 1e−6 | 1e−4 |

The results are roughly consistent with the previous results, with only marginal differences.

Note: These results are obtained by running the fixed code once with the original parameters. The code has been integrated into the [MMRec](https://github.com/enoche/MMRec) repository. You are welcome to modify the parameters and run the code further.

**Comment by MeycL** [comment]
Thanks for your reply.
